### ISSUE TITLE
Whatcha' got goin on here?

### ISSUE THREAD

**Issue by MarkMurphy** [jayphelps/redux-transaction#1]
Hey! I've started using redux-observable today (previously using redux-thunk). I'm at a stage now where my components no longer have any state because I was previously using the promises returned by my thunks to do stuff like `this.setState({ isLoading: true|false })` when they resolve or reject.

Now that I can't do that anymore (which is for the best anyway), question is where / how the heck do I structure my redux store to hold the state of CRUD requests which again, was previously maintained in my container components. 

I just came across this repository of yours which looks like it's trying to address this problem but also noticed it hasn't been touched it in a long time. Have you given up on this or figured out some other way of doing this?

**Comment by jayphelps** [comment]
I am using this, but it has a lot of rough edges so I definitely wouldn't recommend it. Haven't had an opportunity to hash out any updates from my learnings and unlikely to have time any time soon as I'm working on other stuff. :shipit: Sorry I can't help further!
